# Generated by Django 3.2.5 on 2021-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compant_name', models.CharField(max_length=100)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=100)),
                ('job_des', models.TextField(blank=True, max_length=1000, null=True)),
                ('salary', models.IntegerField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
